// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzkmZ34GX0wsH_oal-8regRuyr2b9-lGM',
    appId: '1:329106725592:web:c84bf3c51c48a3c29715ad',
    messagingSenderId: '329106725592',
    projectId: 'videos-992c8',
    authDomain: 'videos-992c8.firebaseapp.com',
    storageBucket: 'videos-992c8.firebasestorage.app',
    measurementId: 'G-4MKSM348EF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdumQU3NxPzs13U0ICkHBlzZp1VtC8zRY',
    appId: '1:329106725592:android:d2111a29c3f236819715ad',
    messagingSenderId: '329106725592',
    projectId: 'videos-992c8',
    storageBucket: 'videos-992c8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdCCFF7AUuQeyeCUzRmf0rvEcYGZ3oArQ',
    appId: '1:329106725592:ios:03bd3d261b3fe1f49715ad',
    messagingSenderId: '329106725592',
    projectId: 'videos-992c8',
    storageBucket: 'videos-992c8.firebasestorage.app',
    iosBundleId: 'com.example.calculators',
  );
}
